### sign up
POST http://localhost:8080/signup
Content-Type: application/json

{
  "email": "test2@yahoo.fr",
  "name": "test2",
  "password": "test2"
}
### login
POST http://localhost:8080/login
Content-Type: application/json

{
  "email": "admin@yahoo.fr",
  "password": "admin"
}

### access endpoint "/home"
GET http://localhost:8080/api/home
Authorization: Bearer REPLACE_THIS_WITH_TOKEN

